// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFH1qHXG7Iw4N9t4gdRsJ-_U5zwGS8wgA',
    appId: '1:712196425896:web:d86b43027501d2a876da9d',
    messagingSenderId: '712196425896',
    projectId: 'emartplus-a0fcd',
    authDomain: 'emartplus-a0fcd.firebaseapp.com',
    databaseURL: 'https://emartplus-a0fcd-default-rtdb.firebaseio.com',
    storageBucket: 'emartplus-a0fcd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgZo1s-MiMON-_gm1StYHhek5Oq0gYcFs',
    appId: '1:712196425896:android:23c1b2ccf1b2f7d976da9d',
    messagingSenderId: '712196425896',
    projectId: 'emartplus-a0fcd',
    databaseURL: 'https://emartplus-a0fcd-default-rtdb.firebaseio.com',
    storageBucket: 'emartplus-a0fcd.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJAWDb2v6mzGKfxKaemyLhEdNz-EDlngs',
    appId: '1:712196425896:ios:038406c27a6f7bc776da9d',
    messagingSenderId: '712196425896',
    projectId: 'emartplus-a0fcd',
    databaseURL: 'https://emartplus-a0fcd-default-rtdb.firebaseio.com',
    storageBucket: 'emartplus-a0fcd.appspot.com',
    iosBundleId: 'com.example.emartPlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFH1qHXG7Iw4N9t4gdRsJ-_U5zwGS8wgA',
    appId: '1:712196425896:web:ac6ea3c017d8a80776da9d',
    messagingSenderId: '712196425896',
    projectId: 'emartplus-a0fcd',
    authDomain: 'emartplus-a0fcd.firebaseapp.com',
    databaseURL: 'https://emartplus-a0fcd-default-rtdb.firebaseio.com',
    storageBucket: 'emartplus-a0fcd.appspot.com',
  );
}
